import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class FormHitungHari extends javax.swing.JFrame {
    
    // Variabel untuk simpan tanggal klik pertama dan kedua
    private Date tanggalPertama = null;
    private Date tanggalKedua = null;
    
    private String hari;

    /**
     * Creates new form FormHitungHari
     */
    
     // Constructor utama
    public FormHitungHari() {
        initComponents();
        isiComboBulan();
        setTitle("Aplikasi Penghitung Hari");
        setLocationRelativeTo(null);
        setResizable(false);
        pack();

        // Event klik tanggal di JCalendar
        jCalendar1.getDayChooser().addPropertyChangeListener("day", evt -> {
            handleTanggalDipilih();
        });
    }

    // Isi combo box bulan
    private void isiComboBulan() {
        jComboBox1.removeAllItems();
        String[] bulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni",
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
        for (String b : bulan) {
            jComboBox1.addItem(b);
        }
        jComboBox1.setSelectedIndex(0);
        SpinnerTahun.setValue(2025);
    }

    // 🔹 Cek tahun kabisat
    private boolean isKabisat(int tahun) {
        return (tahun % 4 == 0 && tahun % 100 != 0) || (tahun % 400 == 0);
    }
    
    // 🔹 Format hari ke bahasa Indonesia
    private String formatHari(String hari) {
        return switch (hari.toUpperCase()) {
            case "MONDAY" -> "Senin";
            case "TUESDAY" -> "Selasa";
            case "WEDNESDAY" -> "Rabu";
            case "THURSDAY" -> "Kamis";
            case "FRIDAY" -> "Jumat";
            case "SATURDAY" -> "Sabtu";
            case "SUNDAY" -> "Minggu";
            default -> hari;
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InputBulan = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        InputTahun = new javax.swing.JLabel();
        SpinnerTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        HasilPerhitungan = new javax.swing.JLabel();
        BulanTahun = new javax.swing.JTextField();
        TahunKeluar = new javax.swing.JTextField();
        HariPertama = new javax.swing.JTextField();
        HariKedua = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        PerhitunganSelisih = new javax.swing.JLabel();
        PilihTanggal = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        DariTahun = new javax.swing.JTextField();
        SampaiTahun = new javax.swing.JTextField();
        TotalSelisih = new javax.swing.JTextField();
        btnSelisih = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APLIKASI PENGHITUNG HARI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        InputBulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputBulan.setForeground(new java.awt.Color(255, 255, 255));
        InputBulan.setText("Input Bulan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        InputTahun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputTahun.setForeground(new java.awt.Color(255, 255, 255));
        InputTahun.setText("Input Tahun");

        btnHitung.setBackground(new java.awt.Color(255, 204, 204));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHitung.setText("Hitung ");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        HasilPerhitungan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HasilPerhitungan.setText("Hasil Perhitungan");

        HariPertama.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        HariPertama.setText("Hari Pertama:");

        HariKedua.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        HariKedua.setText("Hari Terakhir:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(HasilPerhitungan)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HariKedua)
                    .addComponent(HariPertama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BulanTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TahunKeluar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HasilPerhitungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BulanTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(TahunKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HariPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HariKedua, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        PerhitunganSelisih.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PerhitunganSelisih.setText("Perhitungan Selisih");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(PerhitunganSelisih)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PerhitunganSelisih)
                .addContainerGap())
        );

        PilihTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PilihTanggal.setForeground(new java.awt.Color(255, 255, 255));
        PilihTanggal.setText("Silahkan Pilih Tanggal:");

        btnReset.setBackground(new java.awt.Color(153, 153, 153));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(153, 153, 153));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        DariTahun.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        DariTahun.setText("Dari:");

        SampaiTahun.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        SampaiTahun.setText("Sampai:");
        SampaiTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SampaiTahunActionPerformed(evt);
            }
        });

        TotalSelisih.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TotalSelisih.setText("Selisih:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SampaiTahun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(TotalSelisih)
                    .addComponent(DariTahun))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DariTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SampaiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSelisih.setBackground(new java.awt.Color(153, 153, 153));
        btnSelisih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelisih.setText("Hitung Selisih");
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });

        Keluar.setBackground(new java.awt.Color(153, 153, 153));
        Keluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PilihTanggal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(InputBulan)
                                            .addGap(50, 50, 50)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnReset)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnKeluar)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(InputTahun)
                                        .addGap(46, 46, 46)
                                        .addComponent(SpinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSelisih)
                                .addGap(18, 18, 18)
                                .addComponent(Keluar)
                                .addGap(63, 63, 63)))
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputBulan))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SpinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputTahun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PilihTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(179, 179, 179))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        jComboBox1.setSelectedIndex(0);
        SpinnerTahun.setValue(2025);
        jCalendar1.setDate(new Date());
        BulanTahun.setText("");
        TahunKeluar.setText("");
        HariPertama.setText("");
        HariKedua.setText("");
        DariTahun.setText("");
        SampaiTahun.setText("");
        TotalSelisih.setText("");
        tanggalPertama = null;
        tanggalKedua = null;        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void SampaiTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SampaiTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SampaiTahunActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try {
            int bulan = jComboBox1.getSelectedIndex() + 1;
            int tahun = (int) SpinnerTahun.getValue();

            LocalDate tanggal = LocalDate.of(tahun, bulan, 1);
            int jumlahHari = tanggal.lengthOfMonth();
            String hariPertama = tanggal.getDayOfWeek().toString();
            String hariTerakhir = tanggal.withDayOfMonth(jumlahHari).getDayOfWeek().toString();

            // Tampilkan Bulan dan Tahun
            BulanTahun.setText("Bulan: " + jComboBox1.getSelectedItem() + " " + tahun);

            // Tampilkan tahun + status kabisat
            TahunKeluar.setText("Tahun: " + tahun + (isKabisat(tahun) ? " (Kabisat)" : " (Bukan Kabisat)"));

            // Hari pertama dan terakhir
            HariPertama.setText("Hari Pertama: " + formatHari(hariPertama));
            HariKedua.setText("Hari Terakhir: " + formatHari(hariTerakhir));

            JOptionPane.showMessageDialog(this,
                    "Jumlah hari pada " + jComboBox1.getSelectedItem() + " " + tahun +
                    " adalah " + jumlahHari + " hari.",
                    "Hasil Perhitungan", JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan input!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    // Klik 2 kali tanggal → hitung selisih
    private void handleTanggalDipilih() {
        Date tanggalDipilih = jCalendar1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy", new Locale("id", "ID"));

        if (tanggalPertama == null) {
            // klik pertama
            tanggalPertama = tanggalDipilih;
            DariTahun.setText("Dari: " + sdf.format(tanggalPertama));
            SampaiTahun.setText("");
            TotalSelisih.setText("");
        } else if (tanggalKedua == null) {
            // klik kedua
            tanggalKedua = tanggalDipilih;
            SampaiTahun.setText("Sampai: " + sdf.format(tanggalKedua));

            LocalDate dari = tanggalPertama.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            LocalDate sampai = tanggalKedua.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

            long selisihHari = Math.abs(ChronoUnit.DAYS.between(dari, sampai));
            TotalSelisih.setText("Selisih: " + selisihHari + " hari");

            JOptionPane.showMessageDialog(this,
                    "Selisih antara " + sdf.format(tanggalPertama) + " dan "
                    + sdf.format(tanggalKedua) + " adalah " + selisihHari + " hari.",
                    "Hasil Selisih", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // klik ketiga → reset
            tanggalPertama = tanggalDipilih;
            tanggalKedua = null;
            DariTahun.setText("Dari: " + sdf.format(tanggalPertama));
            SampaiTahun.setText("");
            TotalSelisih.setText("");
        }
    }
    
    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        try {
            // Ambil dua tanggal dari dua kalender
            Date tanggalDari = jCalendar1.getDate();
            Date tanggalSampai = jCalendar1.getDate();

            if (tanggalDari == null || tanggalSampai == null) {
                JOptionPane.showMessageDialog(this, "Silakan pilih kedua tanggal terlebih dahulu!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy", new Locale("id", "ID"));
            LocalDate dari = tanggalDari.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            LocalDate sampai = tanggalSampai.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            long selisihHari = Math.abs(ChronoUnit.DAYS.between(dari, sampai));

            DariTahun.setText("Dari: " + sdf.format(tanggalDari));
            SampaiTahun.setText("Sampai: " + sdf.format(tanggalSampai));
            TotalSelisih.setText("Selisih: " + selisihHari + " hari");

            JOptionPane.showMessageDialog(this,
                    "Selisih antara " + sdf.format(tanggalDari) + " dan " +
                    sdf.format(tanggalSampai) + " adalah " + selisihHari + " hari.",
                    "Hasil Selisih", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan dalam menghitung selisih!");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSelisihActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHitungHari().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BulanTahun;
    private javax.swing.JTextField DariTahun;
    private javax.swing.JTextField HariKedua;
    private javax.swing.JTextField HariPertama;
    private javax.swing.JLabel HasilPerhitungan;
    private javax.swing.JLabel InputBulan;
    private javax.swing.JLabel InputTahun;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel PerhitunganSelisih;
    private javax.swing.JLabel PilihTanggal;
    private javax.swing.JTextField SampaiTahun;
    private javax.swing.JSpinner SpinnerTahun;
    private javax.swing.JTextField TahunKeluar;
    private javax.swing.JTextField TotalSelisih;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelisih;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}